DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;


CREATE TABLE ROLES (
    RID SERIAL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL UNIQUE CHECK (NAME IN ('ADMIN', 'USER'))
);


CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	PASSWORD VARCHAR(60) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
    ROLE_ID INT NOT NULL DEFAULT 2,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(RID)
);

INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');